# Generated by Django 3.1.6 on 2021-04-29 07:28

from django.db import migrations, models
import django.utils.timezone
import tenancy.storage


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mirror',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('name', models.CharField(max_length=200, verbose_name='文件名')),
                ('link', models.CharField(max_length=200, verbose_name='文件')),
                ('memo', models.CharField(max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '镜像',
                'verbose_name_plural': '镜像列表',
            },
        ),
        migrations.CreateModel(
            name='Soft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('name', models.CharField(max_length=200, verbose_name='文件名')),
                ('link', models.FileField(storage=tenancy.storage.QiniuStorage(), upload_to='', verbose_name='文件')),
                ('memo', models.CharField(max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '软件',
                'verbose_name_plural': '软件列表',
            },
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': '文件', 'verbose_name_plural': '文件列表'},
        ),
        migrations.AlterField(
            model_name='file',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='file',
            name='link',
            field=models.FileField(storage=tenancy.storage.QiniuStorage(), upload_to='', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='file',
            name='memo',
            field=models.CharField(max_length=200, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=200, verbose_name='文件名'),
        ),
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(max_length=200, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='file',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间'),
        ),
    ]
